Added environment variable `function_region`
omerxx/drone-lambda-plugin pull request #3
Opened 2018-01-17 13:54 UTC by denizs

The additions in this PR let's you specify a `function_region` in case your lambda is deployed in another region (eu-central-1 in my case).

2018-05-11 20:46 UTC, omerxx requested changes
Sorry for the huge delay - Awesome addition!
Just need to remove some of the changes I don't need in my own repo.
Thanks again!

2018-05-11 20:46 UTC, omerxx commented on .drone.yml
> +    repo: enlyze/drone-lambda-plugin
You've changed the repo used to push the container which I can't have in the PR

2018-05-11 20:46 UTC, omerxx commented on .drone.yml.sig
> +<!DOCTYPE html>
What is the purpose of this file?

2018-08-31 11:31 UTC, zakkg3 commented
https://github.com/aws/aws-sdk-go/blob/master/service/lambda/api.go#L6717

// AWS Lambda also allows you to specify a partial ARN (for example, account-id:Thumbnail).

2018-08-31 23:02 UTC, omerxx commented
@zakkg3 Care to make the required additions?

2020-06-10 16:53 UTC, omerxx commented
Closing, fixed in #6

2020-06-10 16:53 UTC, closed without merging